class Subjects {
  static const List<String> allSubjects = [
    'Matematik',
    'Fizik',
    'Kimya',
    'Biyoloji',
    'Türkçe',
    'Edebiyat',
    'Tarih',
    'Coğrafya',
    'Felsefe',
    'İngilizce',
    'Almanca',
    'Fransızca',
    'Bilgisayar Bilimi',
    'Robotik',
    'Müzik',
    'Resim',
    'İspanyolca',
    'Rusça',
    'Arapça',
    'İtalyanca',
    'Geometri',
    'Mantık',
    'Ekonomi',
    'İstatistik',
    'Astronomi',
  ];
}
